name: Deploy Static Site

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install SSH client
      run: sudo apt-get install openssh-client -y

    - name: Copy files to EC2
      env:
        SSH_PRIVATE_KEY: ${{ secrets.AWS_SSH_KEY }}
        SSH_USER: ${{ secrets.AWS_SSH_USER }}
        HOST: ${{ secrets.AWS_HOST }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan $HOST >> ~/.ssh/known_hosts
        rsync -avz --delete -e "ssh -i ~/.ssh/id_rsa" ./ $SSH_USER@$HOST:/var/www/html/
