version: 1
frontend:
  phases:
    preBuild:
      commands:
        - npm install
    build:
      commands:
        - npm run build # Adjust based on your build command
  artifacts:
    baseDirectory: build # Adjust based on your build output directory
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
